### ISSUE TITLE
Identify modules that depend on installation of DAGMC

### ISSUE THREAD

**Issue by gonuke** [cnerg/pyne#5]
All PyMOAB usage depends on a valid MOAB installation, but some also depnd on a valid DAGMC installation.  We need to document which those are, probably by trying to build PyNE without DAGMC and looking for failures to build or test.

**Comment by kkiesling** [comment]
The pyne modules and scripts that explicitly depend on DAGMC, via the `pyne/dagmc.pyx` module (because they load a DAGMC geometry file), are:

- `pyne/r2s.py`
- `pyne/partisn.py`
- `scripts/r2s.py`
- `scripts/gtcadis.py`

Other modules just depend on the output from `pyne/dagmc.discretize_geom` but don't otherwise require the `pyne/dagmc.pyx` module directly:

- `mesh.py`
- `alara.py`

**Comment by gonuke** [comment]
Thanks for this summary @kkiesling.  We’ve created issues to address these: 
* [x] #17 for `partisan.py`
* [ ] #18 for the `r2s.py` module

I think it’s ok if the scripts depend on DAGMC, as long as their tests raise `SkipTest` when DAGMC is missing.
